# ĞšĞ¾Ğ½Ñ„Ğ¸Ğ³ÑƒÑ€Ğ°Ñ†Ğ¸Ñ Ğ´Ğ»Ñ Velocity
telegram:
  token: ""
  chats: []

messages:
  server_started: "ğŸ”µ **ĞŸÑ€Ğ¾ĞºÑĞ¸-ÑĞµÑ€Ğ²ĞµÑ€ Ğ·Ğ°Ğ¿ÑƒÑ‰ĞµĞ½!**"
  server_stopped: "ğŸ”´ **ĞŸÑ€Ğ¾ĞºÑĞ¸-ÑĞµÑ€Ğ²ĞµÑ€ Ğ²Ñ‹ĞºĞ»ÑÑ‡ĞµĞ½!**"
  player_logged_in: "âœ… **Ğ˜Ğ³Ñ€Ğ¾Ğº Ğ·Ğ°ÑˆĞµĞ»**: %player%"
  player_logged_out: "âŒ **Ğ˜Ğ³Ñ€Ğ¾Ğº Ğ²Ñ‹ÑˆĞµĞ»**: %player%"
  player_switched_server: "ğŸ”„ **Ğ˜Ğ³Ñ€Ğ¾Ğº ÑĞ¼ĞµĞ½Ğ¸Ğ» ÑĞµÑ€Ğ²ĞµÑ€**: %player%\nâ¡ **%previous_server%** â†’ **%new_server%**"
  player_joined_server: "â¡ **Ğ˜Ğ³Ñ€Ğ¾Ğº Ğ·Ğ°ÑˆĞµĞ» Ğ½Ğ° ÑĞµÑ€Ğ²ĞµÑ€**: %player%\nğŸŸ¢ **Ğ¡ĞµÑ€Ğ²ĞµÑ€**: %new_server%"


