# –ö–æ–Ω—Ñ–∏–≥—É—Ä–∞—Ü–∏—è –¥–ª—è Velocity
telegram:
  token: "YOUR_BOT_TOKEN"
  chats:
    - "chat_id_1"
    - "chat_id_2"

messages:
  server_started: "üîµ **–ü—Ä–æ–∫—Å–∏-—Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω!**"
  server_stopped: "üî¥ **–ü—Ä–æ–∫—Å–∏-—Å–µ—Ä–≤–µ—Ä –≤—ã–∫–ª—é—á–µ–Ω!**"
  player_logged_in: "‚úÖ **–ò–≥—Ä–æ–∫ –∑–∞—à–µ–ª**: %player%"
  player_logged_out: "‚ùå **–ò–≥—Ä–æ–∫ –≤—ã—à–µ–ª**: %player%"
  player_switched_server: "üîÑ **–ò–≥—Ä–æ–∫ —Å–º–µ–Ω–∏–ª —Å–µ—Ä–≤–µ—Ä**: %player%\n‚û° **%previous_server%** ‚Üí **%new_server%**"
  player_joined_server: "‚û° **–ò–≥—Ä–æ–∫ –∑–∞—à–µ–ª –Ω–∞ —Å–µ—Ä–≤–µ—Ä**: %player%\nüü¢ **–°–µ—Ä–≤–µ—Ä**: %new_server%"

updater:
  enabled: true
